# Generated by Django 5.2.1 on 2025-07-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='note',
            field=models.CharField(default='NO note', max_length=100),
        ),
    ]
