# Generated by Django 5.2.1 on 2025-07-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='note',
        ),
    ]
